### ISSUE TITLE
Help to configure

### ISSUE THREAD

**Issue by almeidaah** [agriya/oliker#2]
Hi Guys, I'm having some small problems running `grunt build:dev --force` and `grunt serve`, it runs but feels like missing a lot of images and validations(in register, for example).

Also, I can't load database with that "copy" instructions, the character "/." isnt working on pgadmin... 

Could you help me with that problems? 

Thanks in advance! :D

**Comment by rrjanbiah** [comment]
@almeidaah For support, please contact us here https://www.agriya.com/solutions/classified-ads-solution Thank you.
